#!/usr/bin/expect -f

set timeout 2

set name [lindex $argv 0]
set node [lindex $argv 1]
set pawd [lindex $argv 2]
set path [lindex $argv 3]

set src "/home/${name}/.ssh/id_rsa.pub"

spawn scp ${name}@${node}:${src} ${path}
expect {
    "*yes/no*" {send "yes\n";exp_continue}
    "*password:" {send "$pawd\r"}
}

expect "*${name}@${node}*"

