#!/usr/bin/expect -f

set timeout 2

set name [lindex $argv 0]
set node [lindex $argv 1]
set pawd [lindex $argv 2]

spawn ssh ${name}@${node}
expect {
    "*yes/no*" {send "yes\n";exp_continue}
    "*password:" {send "$pawd\r"}
}

expect "*${name}@${node}*"
send "ssh-keygen -t rsa -P ''\r"
expect "*ssh/id_rsa):"
send "\r"
expect {
    "Overwrite (y/n)?" {send "y\n";exp_continue}
    "*${name}@${node}*" {send "exit\r"}
}
expect eof
exit

